import json
import os

from google import genai
from google.genai import types

from prompts import MEDILINK_SYSTEM_INSTRUCTION
from schemas import AssessmentResult

MODEL_NAME = os.environ.get('GEMINI_MODEL', 'gemini-3.5-flash')
TEMPERATURE = float(os.environ.get('GEMINI_TEMPERATURE', '0.3'))

_client = None


def get_client() -> genai.Client:
    global _client
    if _client is None:
        api_key = os.environ.get('GEMINI_API_KEY') or os.environ.get('GOOGLE_API_KEY')
        if not api_key:
            raise ValueError('Set GEMINI_API_KEY or GOOGLE_API_KEY in MediLink-backend/.env')
        _client = genai.Client(api_key=api_key)
    return _client


def _assessment_config() -> types.GenerateContentConfig:
    return types.GenerateContentConfig(
        system_instruction=MEDILINK_SYSTEM_INSTRUCTION,
        temperature=TEMPERATURE,
        max_output_tokens=2048,
        response_mime_type='application/json',
        response_json_schema=AssessmentResult.model_json_schema(),
    )


def _chat_config(system_instruction: str) -> types.GenerateContentConfig:
    return types.GenerateContentConfig(
        system_instruction=system_instruction,
        temperature=TEMPERATURE,
        max_output_tokens=1024,
    )


def _extract_text(response) -> str:
    if not response.candidates:
        raise ValueError('No response generated by the model.')
    text = response.text
    if not text:
        raise ValueError('Empty response from the model.')
    return text


def generate_assessment(prompt: str) -> dict:
    response = get_client().models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
        config=_assessment_config(),
    )
    return json.loads(_extract_text(response))


def generate_chat_reply(system_instruction: str, history: list[dict], message: str) -> str:
    contents = _build_chat_contents(history, message)

    response = get_client().models.generate_content(
        model=MODEL_NAME,
        contents=contents,
        config=_chat_config(system_instruction),
    )
    return _extract_text(response)


def _build_chat_contents(history: list[dict], message: str) -> list:
    contents = []
    for item in history:
        role = 'model' if item['role'] == 'assistant' else 'user'
        contents.append(types.Content(role=role, parts=[types.Part(text=item['content'])]))
    contents.append(types.Content(role='user', parts=[types.Part(text=message)]))
    return contents


def stream_chat_reply(system_instruction: str, history: list[dict], message: str):
    contents = _build_chat_contents(history, message)

    for chunk in get_client().models.generate_content_stream(
        model=MODEL_NAME,
        contents=contents,
        config=_chat_config(system_instruction),
    ):
        if chunk.text:
            yield chunk.text
